services:
  - type: web
    name: school-certificates
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn school_certificates.wsgi:application --preload --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: <your-secret-key>
      - key: DATABASE_URL
        fromDatabase:
          name: school-certificates-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: school_certificates.settings.production
    databases:
      - name: school-certificates-db

databases:
  - name: school-certificates-db
    postgresVersion: 13
    region: oregon
    disk:
      sizeGB: 10
    ipAllowList:
      - 0.0.0.0/0
