services:
  - type: web
    name: django-web-service
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: gunicorn school_certificates.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-y6(m_0ns+jnm3st*u^&ro$ejxy3rwwn@=bwwon2d7mtm18t@q!
      - key: DATABASE_URL
        fromDatabase: postgresql://skoolfyxdb_user:Cy0qNOB77XFsDCVVKPQYsJVv65VB9e0n@dpg-cqcfblg8fa8c73cp0f3g-a/skoolfyxdb
      - key: ALLOWED_HOSTS
        value: skoolflyxcerts.onrender.com
databases:
  - name: skoolfyxdb
    plan: free
    region: oregon
