# Generated by Django 4.2.14 on 2024-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificate_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
