# Generated by Django 4.2.14 on 2024-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_student_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificate_number',
            field=models.PositiveBigIntegerField(editable=False, unique=True),
        ),
    ]
