# Generated by Django 4.2.14 on 2024-07-17 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_student_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificate_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
